/*
 * Copyright (C) 2026 Omega493 and contributors

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef MT_DLP_TESTS
#define MT_DLP_TESTS

#ifndef I_D_LIKE_TO_TEST_MT_DLP
# error \
  Using tests without defining the macro I_D_LIKE_TO_TEST_MT_DLP is probably an error. \
  Please define the macro to make intent clear.
#endif // ^^^ I_D_LIKE_TO_TEST_MT_DLP ^^^

#include "include/pch.hpp"

namespace mt_dlp_tests {

constexpr std::string_view kTestUrls[]{
  "http://example.com",
  "https://example.com",
  "http://www.example.com",
  "https://www.example.com",
  "http://example.co.uk",
  "https://example.co.uk",
  "http://sub.example.com",
  "https://sub.example.com",
  "http://sub.sub.example.com",
  "https://a.b.c.d.e.example.com",
  "https://example.ai",
  "http://example.museum",
  "https://example.travel",
  "http://192.168.1.1",
  "https://10.0.0.1",
  "http://172.16.254.1",
  "https://8.8.8.8",
  "http://1.2.3.4.5.6",
  "http://1.1.1.1",
  "https://127.0.0.1",
  "http://255.255.255.255",
  "https://0.0.0.0",
  "http://198.51.100.1",
  "https://203.0.113.50",
  "http://[2001:db8::1]",
  "https://[2001:db8:3333:4444:5555:6666:7777:8888]",
  "http://[::1]",
  "https://[::ffff:192.0.2.128]",
  "http://[2001:db8::2:1]",
  "https://[fe80::1ff:fe23:4567:890a]",
  "http://[2001:db8:85a3:8d3:1319:8a2e:370:7348]",
  "https://[2001:db8:a0b:12f0::1]",
  "http://[2001:db8::]",
  "https://[::]",
  "http://example.com:80",
  "https://example.com:443",
  "http://example.com:8080",
  "https://192.168.1.1:9090",
  "http://[::1]:8080",
  "https://sub.example.com:65535",
  "http://example.com:1",
  "https://example.com:9999",
  "http://10.0.0.1:22",
  "https://[2001:db8::1]:1234",
  "http://user:pass@example.com",
  "https://user:pass@192.168.1.1",
  "http://user:pass@[::1]",
  "https://user:pass@example.com:8080",
  "http://user@example.com",
  "https://user@10.0.0.1:9090",
  "http://user_name:pass_word@example.com",
  "https://usr123:pwd123!@example.com",
  "http://user%20name:pass%20word@example.com",
  "https://us-er:pa-ss@example.com",
  "http://example.com/",
  "https://example.com/path",
  "http://example.com/path/",
  "https://example.com/path/to/resource",
  "http://example.com/path/to/resource.html",
  "https://example.com/path/to/resource.tar.gz",
  "http://example.com/path/with%20spaces",
  "https://example.com/path/with+plus",
  "http://example.com/path/with.dots/and-dashes",
  "https://example.com/~user/profile",
  "http://example.com/path/with/rfc3986/!$&'()*+,;=",
  "https://example.com/path/to/img.png",
  "http://example.com/path/to/doc.pdf",
  "https://example.com/a/b/c/d/e/f/g/h/i/j/k",
  "http://example.com/path.with.multiple.dots.txt",
  "http://example.com?query=1",
  "https://example.com/path?query=1",
  "http://example.com/path/?q1=a&q2=b",
  "https://example.com/?search=hello+world",
  "http://example.com/api?id=123&token=abc",
  "https://example.com/api?id=123&token=abc&v=2",
  "http://example.com/endpoint?data=%7B%22key%22%3A%22value%22%7D",
  "https://example.com/?q=hello%20world",
  "http://example.com/path?!$&'()*+,;=",
  "https://example.com/?empty=",
  "http://example.com/?=emptykey",
  "https://example.com/?onlykey",
  "http://example.com/?q1=1&q2=2&q3=3&q4=4&q5=5",
  "https://example.com/?array[]=1&array[]=2",
  "http://example.com/path/to/resource?date=2026-08-15",
  "http://example.com#fragment",
  "https://example.com/path#section1",
  "http://example.com/path?query=1#fragment",
  "https://user:pass@example.com:8080/path/to/file.zip?token=123#start",
  "http://192.168.1.1/index.html#top",
  "https://[2001:db8::1]:9090/api/v1/data?type=json#ref",
  "http://sub.domain.example.co.uk/path/with/rfc3986/!$&'()*+,;=@?q=val#frag",
  "http://example.com/path/with/@/symbol?q=@val#@frag",
  "https://example.com/extremely/long/path/that/goes/on/and/on/and/on/and/on/and/on/and/on?with=a&very=long&query=string&that=has&many=parameters#and_a_fragment",
  "http://example.com.",
  "https://example..com",
  "http://.example.com",
  "https://example.com:0080",
  "http://example.com:9999999999999",
  "https://example.com:abcd",
  "http://example.com:/",
  "https://example.com:",
  "http://@example.com",
  "https://user:@example.com",
  "http://user@name:pass@example.com",
  "https://user:pass:extra@example.com",
  "http://:pass@example.com",
  "https://user pass@example.com",
  "http://user!name@example.com",
  "https://user%20name:pass%20word@example.com/",
  "http://user:pass@/path",
  "https://user:pass@",
  "http://",
  "https://.com",
  "http://a.b",
  "https://example",
  "http://-example.com",
  "https://example-.com",
  "http://example.c",
  "https://example_domain.com",
  "http://12345",
  "https://123.com",
  "http://a.com",
  "https://a.b.c",
  "http://[a.b.c.d]",
  "https://example.com:-80",
  "http://256.256.256.256",
  "https://999.999.999.999",
  "http://1.1.1",
  "https://1.1.1.1.1",
  "http://0",
  "https://0.0.0",
  "http://[2001:db8::G]",
  "https://[2001:db8::1",
  "http://2001:db8::1]",
  "https://2001:db8::1",
  "http://[::1]:",
  "https://[::1]:abc",
  "http://[v1.09+::1]",
  "https://[::ffff:192.168.1.1]",
  "http://[fe80::1%lo0]",
  "https://example.com/path with space",
  "http://example.com/path/<>",
  "https://example.com/path/{}",
  "http://example.com/path/|",
  "https://example.com/path/\\",
  "http://example.com/path/^",
  "https://example.com/path/[]",
  "http://example.com/path/\"quote\"",
  "https://example.com/path/%00",
  "http://example.com/path/..",
  "https://example.com/path/.",
  "http://example.com//",
  "https://example.com///path",
  "http://example.com/path?",
  "https://example.com/path#",
  "http://example.com/path?q=?",
  "https://example.com/path#?",
  "http://example.com/path?q=/",
  "https://example.com/path#/",
  "http://example.com/@user",
  "https://example.com/path:80",
  "http://example.com/path;param",
  "https://example.com/path,param",
  "http://example.com/path$param",
  "https://example.com/path%",
  "http://example.com/?q=value#frag#ment",
  "https://example.com/?q=a|b",
  "http://example.com/#frag<ment>",
  "https://example.com/?q={val}",
  "http://example.com/?q=[val]",
  "https://example.com/?q=^val",
  "http://example.com/?q=\\val",
  "https://example.com/?q=\"val\"",
  "http://example.com/?q=",
  "https://example.com/&#",
  "http://example.com/?#",
  "https://example.com/#?",
  "http://example.com/?q=val%2Bue",
  "https://example.com/#frag%20ment",
  "http://example.com/path?q=1&q=2",
  "https://example.com/?a=1&b=2#c=3",
  "http://example.com/path?query?another",
  "https://example.com/path#frag1#frag2",
  "http://example.com/path?q=v#f?q=v",
  "https://example.com/path?q=a%20b%20c#f%20g%20h",
  "http://example.com/path!$&'()*+,;=",
  "https://example.com/path~tilde",
  "http://example.com/path-hyphen",
  "https://example.com/path_underscore",
  "http://example.com/path.dot",
  "https://example.com/path:colon",
  "http://example.com/path@at",
  "https://example.com/path%zz",
  "http://www.url;with;colon.com"
};

} // mt_dlp_test

#endif // MT_DLP_TESTS
