name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cc'
      - '**.hpp'
      - '**.cpp'
      - '**.cxx'
      - '**/CMakeLists.txt'
      - '**.cmake'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cc'
      - '**.hpp'
      - '**.cpp'
      - '**.cxx'
      - '**/CMakeLists.txt'
      - '**.cmake'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        dnf install make cmake ninja-build gcc g++ libcurl-devel ftxui-devel clang lld git -y

    - name: Configure with Preset
      run: |
        cmake --preset=linux-x64-github-actions

    - name: Build with Preset
      run: cmake --build --preset=linux-x64-github-actions
